#!/bin/bash
#This file is part of CD-MOJ.
#
#CD-MOJ is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Foobar is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Foobar.  If not, see <http://www.gnu.org/licenses/>.


#bash build-and-test.sh cpp ribas-ac.cpp sample-problem/
TEMP=$(mktemp)
TOREMOVE=

function sai()
{
  rm $TEMP
  rm -f $TEMP.*
  rm -rf $TOREMOVE
}

trap sai EXIT


PROBLEMDIR=$(realpath $1)

cd $(dirname $0)

if [[ ! -e build-and-test.sh ]]; then
  stat build-and-test.sh
  exit 1
fi

declare -A ULIMITS TLMOD
[[ -e $PROBLEMDIR/conf ]] && source $PROBLEMDIR/conf

#create dummy TL file (por host: build-and-test lê tl.<host> primeiro), removido depois
HOSTNAME="${HOSTNAME:-$(hostname)}"
TLHOST="$PROBLEMDIR/tl.$HOSTNAME"
[[ -z "$CALIBRATIONTL" ]] && CALIBRATIONTL=5
echo "TL[default]=$CALIBRATIONTL" > "$TLHOST"

# coleta o report.html de cada solução (o agente sobe ao MOJ p/ o autor abrir no editor)
CALIBREPORTS="$PROBLEMDIR/.calib-reports"; rm -rf "$CALIBREPORTS" 2>/dev/null; mkdir -p "$CALIBREPORTS" 2>/dev/null
save_report(){ [[ -s "$1/report.html" ]] && cp "$1/report.html" "$CALIBREPORTS/$2.html" 2>/dev/null; }

# find -ac solutions
WORSTTIME=0.01
declare -A WORSTTIMEPERLANG
declare -A LANGOK          # linguagens que tiveram >=1 solução good Accepted neste host

echo "AC solutions:"
for AC in $PROBLEMDIR/sols/good/*; do
  echo "${AC##*/}:"
  LANG=${AC##*.}
  [[ ! -n "${WORSTTIMEPERLANG[$LANG]}" ]] && WORSTTIMEPERLANG[$LANG]=0.01

  mkfifo $TEMP.coprocout
  export ALLOWPARALLELTEST=n
  coproc bash build-and-test.sh ${AC##*.} $AC $PROBLEMDIR $ALLOWTLEDURINGCALIBRATION &>$TEMP.coprocout
  #read -u ${COPROC[0]} T
  exec 7<$TEMP.coprocout
  read -u 7 T
  while read L; do
    [[ "$L" =~ "EXECTIME" ]] || continue;
    read l l ET SMALLRESP <<< "$L"
    printf " $ET"
    [[ "$SMALLRESP" != "AC" ]] && printf "($SMALLRESP)"
    if [[ "$SMALLRESP" =~ "AC" ]] && echo "$ET > ${WORSTTIMEPERLANG[$LANG]}"|bc |grep -q 1; then
      WORSTTIMEPERLANG[$LANG]=$ET
    fi
  done <<< $(tail -f --pid=$COPROC_PID $T/run-trace.log)
  echo

  read -u 7 A
  if [[ "${A}" =~ "Accepted" ]]; then
    LANGOK[$LANG]=1
  elif [[ "${A}" =~ "Time Limit Exceeded" && "$ALLOWTLEDURINGCALIBRATION" == "y" ]]; then
    LANGOK[$LANG]=1
  else
    # ROBUSTEZ: NÃO aborta a calibração inteira por uma solução (toolchain ausente no
    # juiz, erro de ambiente, ou solução realmente quebrada). Pula a linguagem e segue —
    # o juiz reporta a falha ao MOJ (visível sem ssh). Só emite TL p/ linguagens que passaram.
    echo "$AC got '${A:-<sem veredito>}', was waiting Accepted (linguagem $LANG NÃO calibrada neste host). Check ${T}"
  fi
  echo "Verdict: $A"
  echo
  save_report "$T" "good-${AC##*/}"
  TOREMOVE+=" ${T}"
  exec 7<&-
  rm -f $TEMP.coprocout
done

TLMULT=1.35

[[ -n "${TLMOD[calibrafactor]}" ]] && TLMULT=${TLMOD[calibrafactor]}

BESTTIME=10000

rm -f "$TLHOST"
echo "#Generated by calibreitor on $HOSTNAME ($(date -R))" > "$TLHOST"

for t in ${!WORSTTIMEPERLANG[@]}; do
  [[ -n "${LANGOK[$t]}" ]] || continue     # só emite TL p/ linguagens que passaram aqui
  WORSTTIMEPERLANG[$t]="$(echo "$TLMULT * ${WORSTTIMEPERLANG[$t]} + 0.02"|bc -l)"
  echo "TL[$t]=${WORSTTIMEPERLANG[$t]}" >> "$TLHOST"
  if echo "${WORSTTIMEPERLANG[$t]} < $BESTTIME"|bc|grep -q 1; then
    BESTTIME=${WORSTTIMEPERLANG[$t]}
  fi
done

# nenhuma linguagem calibrou (todas faltaram/falharam) -> fallback sensato, não 10000
[[ "$BESTTIME" == 10000 ]] && BESTTIME="$CALIBRATIONTL"
echo "TL[default]=$BESTTIME" >> "$TLHOST"
# tl genérico = fallback p/ hosts sem calibração própria (NFS compartilhado)
cp -f "$TLHOST" "$PROBLEMDIR/tl"

echo "Calibrated TL ($HOSTNAME):"
tail -n+1 "$TLHOST"

# Modo rápido (calibração sob demanda no modelo cache): só as good bastam p/ o TL.
# Pular pass/slow/wrong evita rodar dezenas de soluções/linguagens a cada 1ª submissão.
if [[ -n "$CALIBRATE_ONLY_GOOD" ]]; then
  echo; echo "(CALIBRATE_ONLY_GOOD: pulando verificação verbose de pass/slow/wrong)"
  exit 0
fi

for OTHERSOL in pass slow wrong; do
  [[ ! -d "$PROBLEMDIR/sols/$OTHERSOL" ]] && continue
  echo
  echo "${OTHERSOL^^} solutions:"
  for TLs in $PROBLEMDIR/sols/$OTHERSOL/*; do
    if [[ ! -e $TLs ]]; then echo none; continue;fi
    echo "${TLs##*/}:"
    LANG="${TLs##*.}"
    mkfifo $TEMP.coproc
    coproc bash build-and-test.sh ${TLs##*.} $TLs $PROBLEMDIR y >$TEMP.coproc
    exec 7<$TEMP.coproc
    read -u 7 T
    tail -f --pid=$COPROC_PID $T/run-trace.log|
      while read L; do
        [[ "$L" =~ "EXECTIME" ]] || continue;
        read l l ET SMALLRESP <<< "$L"
        printf "$ET($SMALLRESP) "
      done
    echo
    read -u 7 BIGRESP
    echo "Verdict: $BIGRESP"
    save_report "$T" "$OTHERSOL-${TLs##*/}"
    exec 7<&-
    rm -f $TEMP.coproc
    TOREMOVE+=" ${T}"
  done
done
